### ISSUE TITLE
Missing "engines.inkdrop" field in package.json

### ISSUE THREAD

**Issue by craftzdog** [azu/inkdrop-move-notes#1]
Hi, thanks for creating the plugin!
I found that your plugin does not have "engines.inkdrop" field in its package.json file.
Your plugin is currently not listed in [the plugin registry](https://my.inkdrop.app/plugins/recency) because it can't ensure the compatibility with the current app version.
Please edit package.json like so:

```json
  "engines": {
    "inkdrop": "^4.x"
  },
```

Thanks again for your contribution.

**Comment by azu** [comment]
Thanks
